INSERT INTO student(name, birthday, groupnumber) VALUES ('John', '20200102', 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Chris','20200105', 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Carl','20200202', 1);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Oliver','20200202', 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('James','20200202', 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Lucas','20200202', 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Henry','20200202', 2);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Jacob','20200202', 3);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Logan','20200202',3);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Fred','20200202', 4);
INSERT INTO student(name, birthday, groupnumber) VALUES ('Adam','20200202', 5);
INSERT INTO subject(name, grade) VALUES ('Art', 1);
INSERT INTO subject(name, grade) VALUES ('Music', 1);
INSERT INTO subject(name, grade) VALUES ('Geography', 2);
INSERT INTO subject(name, grade) VALUES ('History', 2);
INSERT INTO subject(name, grade) VALUES ('PE', 3);
INSERT INTO subject(name, grade) VALUES ('Math', 3);
INSERT INTO subject(name, grade) VALUES ('Science', 4);
INSERT INTO subject(name, grade) VALUES ('IT', 4);
INSERT INTO subject(name, grade) VALUES ('Chemistry', 5);
INSERT INTO subject(name, grade) VALUES ('Biology', 5);
INSERT INTO paymenttype(name) VALUES ('DAILY');
INSERT INTO paymenttype(name) VALUES ('WEEKLY');
INSERT INTO paymenttype(name) VALUES ('MONTHLY');
INSERT INTO payment(student_id, type_id, amount, payment_date) VALUES ((select id from student where name='John'), (select id from paymenttype where name = 'WEEKLY'), 1, '20210301');
INSERT INTO payment(student_id, type_id, amount, payment_date) VALUES ((select id from student where name='Oliver'), (select id from paymenttype where name = 'MONTHLY'), 1,'20210301');
INSERT INTO payment(student_id, type_id, amount, payment_date) VALUES ((select id from student where name='Henry'), (select id from paymenttype where name = 'WEEKLY'), 1,'20210301');
INSERT INTO payment(student_id, type_id, amount, payment_date) VALUES ((select id from student where name='James'), (select id from paymenttype where name = 'DAILY'), 1,'20210301');
INSERT INTO payment(student_id, type_id, amount, payment_date) VALUES ((select id from student where name='Fred'), (select id from paymenttype where name = 'DAILY'),2,'20210301');
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='Chris'), (select id from subject where name='Art'), 8);
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='Oliver'), (select id from subject where name='History'), 5);
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='James'), (select id from subject where name='Geography'), 9);
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='Jacob'), (select id from subject where name='Math'), 4);
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='Logan'), (select id from subject where name='PE'), 9);
INSERT INTO mark(student_id, subject_id, mark) VALUES ((select id from student where name ='Adam'), (select id from subject where name='Chemistry'), 7);