ALTER TABLE student MODIFY COLUMN birthday DATE NOT NULL;
ALTER TABLE mark MODIFY COLUMN student_id BIGINT NOT NULL;
ALTER TABLE mark MODIFY COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE mark ADD CONSTRAINT CHK_MARK CHECK(mark>=1 AND mark<=10);
ALTER TABLE subject MODIFY COLUMN grade INT CHECK grade BETWEEN 1 AND 5;
ALTER TABLE paymenttype ADD UNIQUE(name);
ALTER TABLE payment MODIFY COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment MODIFY COLUMN amount decimal NOT NULL;
ALTER TABLE payment MODIFY COLUMN payment_date DATE NOT NULL;
